/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import gestor.CargarImagenes;
import gestor.GestorConexion;
import java.util.List;
import javax.swing.JButton;
import vo.Cancion;

/**
 *
 * @author Elena
 */
public class PanelAlbumes extends javax.swing.JPanel {
    private VentanaMusica ventana;
    /**
     * Creates new form PanelAlbumes
     */
    public PanelAlbumes(VentanaMusica ventana) {
        initComponents();
        this.ventana = ventana;
        GestorConexion gc = new GestorConexion();
        gc.conectarBBDD(null);
        
        CargarImagenes ci = new CargarImagenes(gc);
        
        javax.swing.SwingUtilities.invokeLater(() -> {

        ci.cargarAlbumes(new JButton[]{
            bAlbumes1, bAlbumes2,bAlbumes3, bAlbumes4,
            bAlbumes5, bAlbumes6,bAlbumes7, bAlbumes8
        });
    });
        
        
        
 
        
    }
    
    
    //creo el metodo para mostrar las canciones en el el "PanelVacio"
    private void mostrarCancionesAlbum(int id_Album) {
    // bbtener canciones usando AlbumDaoImpl de la ventana principal
    List<Cancion> canciones = ventana.getCancionesPorAlbum(id_Album);

    // Mostrar las canciones en PanelVacio
    ventana.mostrarCancionesEnVacio(canciones);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pAlbumes = new javax.swing.JPanel();
        bAlbumes1 = new javax.swing.JButton();
        bAlbumes2 = new javax.swing.JButton();
        bAlbumes3 = new javax.swing.JButton();
        bAlbumes4 = new javax.swing.JButton();
        bAlbumes5 = new javax.swing.JButton();
        bAlbumes6 = new javax.swing.JButton();
        bAlbumes7 = new javax.swing.JButton();
        bAlbumes8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pAlbumes.setBackground(new java.awt.Color(68, 68, 68));
        pAlbumes.setEnabled(false);
        pAlbumes.setPreferredSize(new java.awt.Dimension(294, 936));

        bAlbumes1.setBorderPainted(false);
        bAlbumes1.setContentAreaFilled(false);
        bAlbumes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes1ActionPerformed(evt);
            }
        });

        bAlbumes2.setBorderPainted(false);
        bAlbumes2.setContentAreaFilled(false);
        bAlbumes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes2ActionPerformed(evt);
            }
        });

        bAlbumes3.setBorderPainted(false);
        bAlbumes3.setContentAreaFilled(false);
        bAlbumes3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bAlbumes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes3ActionPerformed(evt);
            }
        });

        bAlbumes4.setBorderPainted(false);
        bAlbumes4.setContentAreaFilled(false);
        bAlbumes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes4ActionPerformed(evt);
            }
        });

        bAlbumes5.setBorderPainted(false);
        bAlbumes5.setContentAreaFilled(false);
        bAlbumes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes5ActionPerformed(evt);
            }
        });

        bAlbumes6.setBorderPainted(false);
        bAlbumes6.setContentAreaFilled(false);
        bAlbumes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes6ActionPerformed(evt);
            }
        });

        bAlbumes7.setBorderPainted(false);
        bAlbumes7.setContentAreaFilled(false);
        bAlbumes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes7ActionPerformed(evt);
            }
        });

        bAlbumes8.setBorderPainted(false);
        bAlbumes8.setContentAreaFilled(false);
        bAlbumes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlbumes8ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lover");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lux");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuando Brille el Sol");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Un verano sin ti");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuando No Se Quien soy");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("So Close to What");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dangerous Woman");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sour");

        javax.swing.GroupLayout pAlbumesLayout = new javax.swing.GroupLayout(pAlbumes);
        pAlbumes.setLayout(pAlbumesLayout);
        pAlbumesLayout.setHorizontalGroup(
            pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(65, 69, Short.MAX_VALUE))
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(pAlbumesLayout.createSequentialGroup()
                                .addComponent(bAlbumes8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        pAlbumesLayout.setVerticalGroup(
            pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumesLayout.createSequentialGroup()
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bAlbumes1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bAlbumes2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)))
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bAlbumes3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAlbumes4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAlbumes5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAlbumes6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAlbumes7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)))
                .addGroup(pAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bAlbumes8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlbumesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50))))
        );

        jScrollPane1.setViewportView(pAlbumes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAlbumes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes6ActionPerformed
        mostrarCancionesAlbum(6); 
    }//GEN-LAST:event_bAlbumes6ActionPerformed

    private void bAlbumes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes7ActionPerformed
        mostrarCancionesAlbum(7); 
    }//GEN-LAST:event_bAlbumes7ActionPerformed

    private void bAlbumes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes8ActionPerformed
       mostrarCancionesAlbum(8);
    }//GEN-LAST:event_bAlbumes8ActionPerformed

    private void bAlbumes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes1ActionPerformed
        
      mostrarCancionesAlbum(1);
    }//GEN-LAST:event_bAlbumes1ActionPerformed

    private void bAlbumes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes2ActionPerformed
      
        mostrarCancionesAlbum(2);
    }//GEN-LAST:event_bAlbumes2ActionPerformed

    private void bAlbumes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes3ActionPerformed
       mostrarCancionesAlbum(3);
    }//GEN-LAST:event_bAlbumes3ActionPerformed

    private void bAlbumes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes4ActionPerformed
      mostrarCancionesAlbum(4);
    }//GEN-LAST:event_bAlbumes4ActionPerformed

    private void bAlbumes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlbumes5ActionPerformed
       mostrarCancionesAlbum(5);
    }//GEN-LAST:event_bAlbumes5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlbumes1;
    private javax.swing.JButton bAlbumes2;
    private javax.swing.JButton bAlbumes3;
    private javax.swing.JButton bAlbumes4;
    private javax.swing.JButton bAlbumes5;
    private javax.swing.JButton bAlbumes6;
    private javax.swing.JButton bAlbumes7;
    private javax.swing.JButton bAlbumes8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pAlbumes;
    // End of variables declaration//GEN-END:variables
}
