/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import java.util.List;
import javax.swing.DefaultListModel;
import vo.Cancion;

/**
 *
 * @author Elena
 */
public class PanelVacio extends javax.swing.JPanel {

    
   private VentanaMusica ventana;
    private DefaultListModel<String> modelo;
    
    
    /**
     * Creates new form PanelVacio
     */
    public PanelVacio(VentanaMusica v) {
        this.ventana = v;
        initComponents();
        
        modelo = new DefaultListModel<>();
        lListaCanciones.setModel(modelo);
        
        configurarEventos();

    }

     
     
     //metodo para que cuando le des dos veces a un elemento en la lista se reproduzca
      private void configurarEventos() {
        lListaCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) {
                int index = lListaCanciones.getSelectedIndex();

                if (index >= 0) {
                    ventana.reproducirDesdeLista(index);
                }
            }
        }
    });
    }

     //metodo para mostrar la lista de canciones con el titulo y el artista en el "PanelVacio"
      public void mostrarCanciones(List<Cancion> canciones) {
        modelo.clear();

        for (Cancion c : canciones) {

            String artista = ventana.getArtistaDeCancion(c.getId());

            modelo.addElement(
                c.getTitulo() + " - " + artista
            );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lListaCanciones = new javax.swing.JList<>();

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));
        jPanel1.setPreferredSize(new java.awt.Dimension(796, 581));

        lListaCanciones.setBackground(new java.awt.Color(68, 68, 68));
        lListaCanciones.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lListaCanciones.setForeground(new java.awt.Color(255, 255, 255));
        lListaCanciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lListaCanciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lListaCanciones;
    // End of variables declaration//GEN-END:variables
}
