/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import gestor.CargarImagenes;
import dao.impl.CancionDaoImpl;
import gestor.GestorConexion;
import gestor.ReproductorMusica;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import vo.Cancion;
import java.io.*;
import java.net.URL;
import java.util.List;

/**
 *
 * @author Elena
 */
public class PanelInicio extends javax.swing.JPanel {
     private VentanaMusica ventana; // referencia a la ventana principal
    /**
     * Creates new form PanelInicio
     */
     
    private GestorConexion gc;
    private ReproductorMusica reproductor;

     
    public PanelInicio(VentanaMusica ventana) {
        this.ventana = ventana;
        this.reproductor = ventana.getReproductor(); 
        initComponents();

        this.gc = ventana.getGestorConexion();
       
    
        CargarImagenes ci = new CargarImagenes(gc);

        javax.swing.SwingUtilities.invokeLater(() -> {

            ci.cargarListas(new JButton[]{
                bInicio1
            });

            ci.cargarCanciones(new JButton[]{
                bInicio2, bInicio3, bInicio4, bInicio5,
                bInicio6, bInicio7, bInicio8, bInicio9
            });

            ci.cargarAlbumes(new JButton[]{
                bInicio10, bInicio11, bInicio12, bInicio13,
                bInicio14, bInicio15, bInicio16, bInicio17
            });

            ci.cargarListas(new JButton[]{
                bInicio18, bInicio19, bInicio20, bInicio21,
                bInicio22, bInicio23, bInicio24, bInicio25
            });

            ci.cargarGeneros(new JButton[]{
                bInicio26, bInicio27, bInicio28, bInicio29,
                bInicio30, bInicio31, bInicio32, bInicio33
            });

        });
        
    }

    
    private void mostrarCancionesListas(int id_Lista) {
            // Obtener canciones usando el GestorCanciones de la ventana principal
            List<Cancion> canciones = ventana.getCancionesPorLista(id_Lista);

            // Mostrar las canciones en PanelVacio
            ventana.mostrarCancionesEnVacio(canciones);
        }
    private void mostrarCancionesAlbum(int id_Album) {
        // Obtener canciones usando el GestorCanciones de la ventana principal
        List<Cancion> canciones = ventana.getCancionesPorAlbum(id_Album);

        // Mostrar las canciones en PanelVacio
        ventana.mostrarCancionesEnVacio(canciones);
    }

    private void mostrarCancionesGeneros(int id_Genero) {
        // Obtener canciones usando el GestorCanciones de la ventana principal
        List<Cancion> canciones = ventana.getCancionesPorGenero(id_Genero);

        // Mostrar las canciones en PanelVacio
        ventana.mostrarCancionesEnVacio(canciones);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spInicio = new javax.swing.JScrollPane();
        pInicio = new javax.swing.JPanel();
        pPortada = new javax.swing.JPanel();
        lAlbum1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        bInicio1 = new javax.swing.JButton();
        spAlbumPopular = new javax.swing.JScrollPane();
        pAlbumPopular = new javax.swing.JPanel();
        lNombreInicio13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lTituloInicio12 = new javax.swing.JLabel();
        lTituloInicio10 = new javax.swing.JLabel();
        lTituloInicio11 = new javax.swing.JLabel();
        lTituloInicio13 = new javax.swing.JLabel();
        lNombreInicio10 = new javax.swing.JLabel();
        lNombreInicio12 = new javax.swing.JLabel();
        lNombreInicio11 = new javax.swing.JLabel();
        lTituloInicio14 = new javax.swing.JLabel();
        lNombreInicio14 = new javax.swing.JLabel();
        lTituloInicio15 = new javax.swing.JLabel();
        lNombreInicio15 = new javax.swing.JLabel();
        lTituloInicio16 = new javax.swing.JLabel();
        lNombreInicio16 = new javax.swing.JLabel();
        lTituloInicio17 = new javax.swing.JLabel();
        lNombreInicio17 = new javax.swing.JLabel();
        bInicio10 = new javax.swing.JButton();
        bInicio11 = new javax.swing.JButton();
        bInicio12 = new javax.swing.JButton();
        bInicio13 = new javax.swing.JButton();
        bInicio14 = new javax.swing.JButton();
        bInicio15 = new javax.swing.JButton();
        bInicio16 = new javax.swing.JButton();
        bInicio17 = new javax.swing.JButton();
        spCancionTendencia = new javax.swing.JScrollPane();
        pCancionTendencias = new javax.swing.JPanel();
        lNombreInicio5 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        lTituloInicio4 = new javax.swing.JLabel();
        lTituloInicio2 = new javax.swing.JLabel();
        lTituloInicio3 = new javax.swing.JLabel();
        lTituloInicio5 = new javax.swing.JLabel();
        bInicio2 = new javax.swing.JButton();
        lNombreInicio2 = new javax.swing.JLabel();
        lNombreInicio4 = new javax.swing.JLabel();
        lNombreInicio3 = new javax.swing.JLabel();
        lTituloInicio6 = new javax.swing.JLabel();
        lNombreInicio6 = new javax.swing.JLabel();
        lTituloInicio7 = new javax.swing.JLabel();
        lNombreInicio7 = new javax.swing.JLabel();
        lTituloInicio8 = new javax.swing.JLabel();
        lNombreInicio8 = new javax.swing.JLabel();
        lTituloInicio9 = new javax.swing.JLabel();
        lNombreInicio9 = new javax.swing.JLabel();
        bInicio3 = new javax.swing.JButton();
        bInicio4 = new javax.swing.JButton();
        bInicio5 = new javax.swing.JButton();
        bInicio6 = new javax.swing.JButton();
        bInicio7 = new javax.swing.JButton();
        bInicio8 = new javax.swing.JButton();
        bInicio9 = new javax.swing.JButton();
        spGeneros = new javax.swing.JScrollPane();
        pGeneros = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        lTituloInicio28 = new javax.swing.JLabel();
        lTituloInicio26 = new javax.swing.JLabel();
        lTituloInicio27 = new javax.swing.JLabel();
        lTituloInicio29 = new javax.swing.JLabel();
        lTituloInicio30 = new javax.swing.JLabel();
        lTituloInicio31 = new javax.swing.JLabel();
        lTituloInicio32 = new javax.swing.JLabel();
        lTituloInicio33 = new javax.swing.JLabel();
        bInicio26 = new javax.swing.JButton();
        bInicio27 = new javax.swing.JButton();
        bInicio28 = new javax.swing.JButton();
        bInicio29 = new javax.swing.JButton();
        bInicio30 = new javax.swing.JButton();
        bInicio31 = new javax.swing.JButton();
        bInicio32 = new javax.swing.JButton();
        bInicio33 = new javax.swing.JButton();
        spListasInicio = new javax.swing.JScrollPane();
        pListasInicio = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        lTituloInicio20 = new javax.swing.JLabel();
        lTituloInicio18 = new javax.swing.JLabel();
        lTituloInicio19 = new javax.swing.JLabel();
        lTituloInicio21 = new javax.swing.JLabel();
        lTituloInicio22 = new javax.swing.JLabel();
        lTituloInicio23 = new javax.swing.JLabel();
        lTituloInicio24 = new javax.swing.JLabel();
        lTituloInicio25 = new javax.swing.JLabel();
        bInicio18 = new javax.swing.JButton();
        bInicio19 = new javax.swing.JButton();
        bInicio20 = new javax.swing.JButton();
        bInicio21 = new javax.swing.JButton();
        bInicio22 = new javax.swing.JButton();
        bInicio23 = new javax.swing.JButton();
        bInicio24 = new javax.swing.JButton();
        bInicio25 = new javax.swing.JButton();

        spInicio.setBackground(new java.awt.Color(68, 68, 68));
        spInicio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spInicio.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pInicio.setBackground(new java.awt.Color(68, 68, 68));
        pInicio.setEnabled(false);

        pPortada.setBackground(new java.awt.Color(43, 41, 41));

        lAlbum1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lAlbum1.setForeground(new java.awt.Color(255, 255, 255));
        lAlbum1.setText("Album recomendado");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taDescripcion.setEditable(false);
        taDescripcion.setBackground(new java.awt.Color(68, 68, 68));
        taDescripcion.setColumns(20);
        taDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        taDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        taDescripcion.setRows(5);
        taDescripcion.setText("\nSumérgete en una selección de canciones \nimprescindibles que están marcando el ritmo del \nmomento. Aquí encontrarás los sonidos más frescos, \nartistas destacados y canciones que ya forman parte \nde las tendencias actuales. Perfecto para descubrir \nnueva música, redescubrir estilos y dejarte llevar por \nlo que está sonando ahora mismo");
        taDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taDescripcion);

        bInicio1.setBorderPainted(false);
        bInicio1.setContentAreaFilled(false);
        bInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPortadaLayout = new javax.swing.GroupLayout(pPortada);
        pPortada.setLayout(pPortadaLayout);
        pPortadaLayout.setHorizontalGroup(
            pPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPortadaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(bInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(pPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAlbum1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        pPortadaLayout.setVerticalGroup(
            pPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPortadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPortadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bInicio1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addGroup(pPortadaLayout.createSequentialGroup()
                        .addComponent(lAlbum1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        spAlbumPopular.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spAlbumPopular.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pAlbumPopular.setBackground(new java.awt.Color(68, 68, 68));

        lNombreInicio13.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio13.setText("Bad Bunny");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Álbumes populares");

        lTituloInicio12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio12.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio12.setText("Cuando Brille el Sol");

        lTituloInicio10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio10.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio10.setText("Lover");

        lTituloInicio11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio11.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio11.setText("Lux");

        lTituloInicio13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio13.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio13.setText("Un verano sin ti");

        lNombreInicio10.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio10.setText("Taylor Swift");

        lNombreInicio12.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio12.setText("La Guardia");

        lNombreInicio11.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio11.setText("Rosalia");

        lTituloInicio14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio14.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio14.setText("Cuando No Se Quien soy");

        lNombreInicio14.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio14.setText("Amaia");

        lTituloInicio15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio15.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio15.setText("So Close to What");

        lNombreInicio15.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio15.setText("Tate McRae");

        lTituloInicio16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio16.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio16.setText("Dangerous Woman");

        lNombreInicio16.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio16.setText("Ariana Grande");

        lTituloInicio17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio17.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio17.setText("Sour");

        lNombreInicio17.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio17.setText("Olivia Rodrigo");

        bInicio10.setBorderPainted(false);
        bInicio10.setContentAreaFilled(false);
        bInicio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio10ActionPerformed(evt);
            }
        });

        bInicio11.setBorderPainted(false);
        bInicio11.setContentAreaFilled(false);
        bInicio11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio11ActionPerformed(evt);
            }
        });

        bInicio12.setBorderPainted(false);
        bInicio12.setContentAreaFilled(false);
        bInicio12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio12ActionPerformed(evt);
            }
        });

        bInicio13.setBorderPainted(false);
        bInicio13.setContentAreaFilled(false);
        bInicio13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio13ActionPerformed(evt);
            }
        });

        bInicio14.setBorderPainted(false);
        bInicio14.setContentAreaFilled(false);
        bInicio14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio14ActionPerformed(evt);
            }
        });

        bInicio15.setBorderPainted(false);
        bInicio15.setContentAreaFilled(false);
        bInicio15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio15ActionPerformed(evt);
            }
        });

        bInicio16.setBorderPainted(false);
        bInicio16.setContentAreaFilled(false);
        bInicio16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio16ActionPerformed(evt);
            }
        });

        bInicio17.setBorderPainted(false);
        bInicio17.setContentAreaFilled(false);
        bInicio17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAlbumPopularLayout = new javax.swing.GroupLayout(pAlbumPopular);
        pAlbumPopular.setLayout(pAlbumPopularLayout);
        pAlbumPopularLayout.setHorizontalGroup(
            pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lNombreInicio10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInicio10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNombreInicio12, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lTituloInicio12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInicio12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTituloInicio13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio13, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lTituloInicio15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lNombreInicio15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInicio15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bInicio16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bInicio17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        pAlbumPopularLayout.setVerticalGroup(
            pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlbumPopularLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                .addComponent(lTituloInicio16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNombreInicio16))
                            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                .addComponent(lTituloInicio15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNombreInicio15))))
                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                .addComponent(lTituloInicio17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNombreInicio17))
                            .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bInicio10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio14, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio15, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio17, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lTituloInicio10)
                                            .addComponent(lTituloInicio11)
                                            .addComponent(lTituloInicio13)
                                            .addComponent(lTituloInicio12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pAlbumPopularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lNombreInicio10)
                                            .addComponent(lNombreInicio11)
                                            .addComponent(lNombreInicio12)
                                            .addComponent(lNombreInicio13)))
                                    .addGroup(pAlbumPopularLayout.createSequentialGroup()
                                        .addComponent(lTituloInicio14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lNombreInicio14)))))))
                .addContainerGap())
        );

        spAlbumPopular.setViewportView(pAlbumPopular);

        spCancionTendencia.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spCancionTendencia.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pCancionTendencias.setBackground(new java.awt.Color(68, 68, 68));

        lNombreInicio5.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio5.setText("RedBone");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Canciones en tendencia");

        lTituloInicio4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio4.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio4.setText("Sweet Caroline");

        lTituloInicio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio2.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio2.setText("Macarena");

        lTituloInicio3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio3.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio3.setText("Viva La Vida");

        lTituloInicio5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio5.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio5.setText("Come and Get your Love");

        bInicio2.setBorderPainted(false);
        bInicio2.setContentAreaFilled(false);
        bInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio2ActionPerformed(evt);
            }
        });

        lNombreInicio2.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio2.setText("Los del Rio");

        lNombreInicio4.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio4.setText("Neil Diamond");

        lNombreInicio3.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio3.setText("Coldplay");

        lTituloInicio6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio6.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio6.setText("Someone Like You");

        lNombreInicio6.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio6.setText("Adele");

        lTituloInicio7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio7.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio7.setText("Wake Me Up");

        lNombreInicio7.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio7.setText("Avicii");

        lTituloInicio8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio8.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio8.setText("We Will Rock You ");

        lNombreInicio8.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio8.setText("Queen");

        lTituloInicio9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio9.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio9.setText("Gasolina");

        lNombreInicio9.setForeground(new java.awt.Color(204, 204, 204));
        lNombreInicio9.setText("Daddy Yankee");

        bInicio3.setBorderPainted(false);
        bInicio3.setContentAreaFilled(false);
        bInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio3ActionPerformed(evt);
            }
        });

        bInicio4.setBorderPainted(false);
        bInicio4.setContentAreaFilled(false);
        bInicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio4ActionPerformed(evt);
            }
        });

        bInicio5.setBorderPainted(false);
        bInicio5.setContentAreaFilled(false);
        bInicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio5ActionPerformed(evt);
            }
        });

        bInicio6.setBorderPainted(false);
        bInicio6.setContentAreaFilled(false);
        bInicio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio6ActionPerformed(evt);
            }
        });

        bInicio7.setBorderPainted(false);
        bInicio7.setContentAreaFilled(false);
        bInicio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio7ActionPerformed(evt);
            }
        });

        bInicio8.setBorderPainted(false);
        bInicio8.setContentAreaFilled(false);
        bInicio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio8ActionPerformed(evt);
            }
        });

        bInicio9.setBorderPainted(false);
        bInicio9.setContentAreaFilled(false);
        bInicio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCancionTendenciasLayout = new javax.swing.GroupLayout(pCancionTendencias);
        pCancionTendencias.setLayout(pCancionTendenciasLayout);
        pCancionTendenciasLayout.setHorizontalGroup(
            pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bInicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lTituloInicio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lNombreInicio2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lNombreInicio4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lTituloInicio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInicio4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTituloInicio5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTituloInicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNombreInicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lNombreInicio9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                        .addComponent(bInicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bInicio8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bInicio9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        pCancionTendenciasLayout.setVerticalGroup(
            pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCancionTendenciasLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lTituloInicio7)
                .addGap(28, 28, 28))
            .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTituloInicio9)
                            .addComponent(lTituloInicio8))
                        .addGap(3, 3, 3)
                        .addComponent(lNombreInicio9))
                    .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bInicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lTituloInicio2)
                                    .addComponent(lTituloInicio3)
                                    .addComponent(lTituloInicio5)
                                    .addComponent(lTituloInicio4))
                                .addGap(3, 3, 3)
                                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNombreInicio3)
                                    .addComponent(lNombreInicio4)
                                    .addComponent(lNombreInicio5)
                                    .addComponent(lNombreInicio2)))
                            .addGroup(pCancionTendenciasLayout.createSequentialGroup()
                                .addComponent(lTituloInicio6)
                                .addGap(3, 3, 3)
                                .addGroup(pCancionTendenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNombreInicio6)
                                    .addComponent(lNombreInicio7)
                                    .addComponent(lNombreInicio8))))))
                .addContainerGap())
        );

        spCancionTendencia.setViewportView(pCancionTendencias);

        spGeneros.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spGeneros.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pGeneros.setBackground(new java.awt.Color(68, 68, 68));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Generos");

        lTituloInicio28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio28.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio28.setText("Reggaeton");

        lTituloInicio26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio26.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio26.setText("Pop");

        lTituloInicio27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio27.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio27.setText("Rock Español");

        lTituloInicio29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio29.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio29.setText("Rock");

        lTituloInicio30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio30.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio30.setText("Electrónica");

        lTituloInicio31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio31.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio31.setText("R&B");

        lTituloInicio32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio32.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio32.setText("Clásica");

        lTituloInicio33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio33.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio33.setText("Indie");

        bInicio26.setBorderPainted(false);
        bInicio26.setContentAreaFilled(false);
        bInicio26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio26ActionPerformed(evt);
            }
        });

        bInicio27.setBorderPainted(false);
        bInicio27.setContentAreaFilled(false);
        bInicio27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio27ActionPerformed(evt);
            }
        });

        bInicio28.setBorderPainted(false);
        bInicio28.setContentAreaFilled(false);
        bInicio28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio28ActionPerformed(evt);
            }
        });

        bInicio29.setBorderPainted(false);
        bInicio29.setContentAreaFilled(false);
        bInicio29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bInicio29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio29ActionPerformed(evt);
            }
        });

        bInicio30.setBorderPainted(false);
        bInicio30.setContentAreaFilled(false);
        bInicio30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio30ActionPerformed(evt);
            }
        });

        bInicio31.setBorderPainted(false);
        bInicio31.setContentAreaFilled(false);
        bInicio31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio31ActionPerformed(evt);
            }
        });

        bInicio32.setBorderPainted(false);
        bInicio32.setContentAreaFilled(false);
        bInicio32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio32ActionPerformed(evt);
            }
        });

        bInicio33.setBorderPainted(false);
        bInicio33.setContentAreaFilled(false);
        bInicio33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGenerosLayout = new javax.swing.GroupLayout(pGeneros);
        pGeneros.setLayout(pGenerosLayout);
        pGenerosLayout.setHorizontalGroup(
            pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGenerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGenerosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTituloInicio26, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bInicio26, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pGenerosLayout.createSequentialGroup()
                                .addComponent(lTituloInicio27, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lTituloInicio28, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lTituloInicio29, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pGenerosLayout.createSequentialGroup()
                                .addComponent(bInicio27, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bInicio28, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bInicio29, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInicio30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGenerosLayout.createSequentialGroup()
                        .addComponent(lTituloInicio31, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lTituloInicio32, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lTituloInicio33, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGenerosLayout.createSequentialGroup()
                        .addComponent(bInicio31, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bInicio32, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(bInicio33, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pGenerosLayout.setVerticalGroup(
            pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGenerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTituloInicio32)
                        .addComponent(lTituloInicio31))
                    .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lTituloInicio33)
                        .addGroup(pGenerosLayout.createSequentialGroup()
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bInicio26, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio27, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio28, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio29, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio30, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio31, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio32, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bInicio33, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pGenerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lTituloInicio26)
                                    .addComponent(lTituloInicio27)
                                    .addComponent(lTituloInicio29)
                                    .addComponent(lTituloInicio28))
                                .addComponent(lTituloInicio30)))))
                .addGap(28, 28, 28))
        );

        spGeneros.setViewportView(pGeneros);

        spListasInicio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spListasInicio.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pListasInicio.setBackground(new java.awt.Color(68, 68, 68));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Listas");

        lTituloInicio20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio20.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio20.setText("Multicolor Musical");

        lTituloInicio18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio18.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio18.setText("Día Perfecto");

        lTituloInicio19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio19.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio19.setText("Te y galletas");

        lTituloInicio21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio21.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio21.setText("Vida Organizada");

        lTituloInicio22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio22.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio22.setText("Hits para sentirme adulta");

        lTituloInicio23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio23.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio23.setText("Grammy en la Ducha");

        lTituloInicio24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio24.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio24.setText("Temazos para llorar");

        lTituloInicio25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTituloInicio25.setForeground(new java.awt.Color(255, 255, 255));
        lTituloInicio25.setText("Temas para Isabel II");

        bInicio18.setBorderPainted(false);
        bInicio18.setContentAreaFilled(false);
        bInicio18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio18ActionPerformed(evt);
            }
        });

        bInicio19.setBorderPainted(false);
        bInicio19.setContentAreaFilled(false);
        bInicio19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio19ActionPerformed(evt);
            }
        });

        bInicio20.setBorderPainted(false);
        bInicio20.setContentAreaFilled(false);
        bInicio20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio20ActionPerformed(evt);
            }
        });

        bInicio21.setBorderPainted(false);
        bInicio21.setContentAreaFilled(false);
        bInicio21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio21ActionPerformed(evt);
            }
        });

        bInicio22.setBorderPainted(false);
        bInicio22.setContentAreaFilled(false);
        bInicio22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio22ActionPerformed(evt);
            }
        });

        bInicio23.setBorderPainted(false);
        bInicio23.setContentAreaFilled(false);
        bInicio23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio23ActionPerformed(evt);
            }
        });

        bInicio24.setBorderPainted(false);
        bInicio24.setContentAreaFilled(false);
        bInicio24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio24ActionPerformed(evt);
            }
        });

        bInicio25.setBorderPainted(false);
        bInicio25.setContentAreaFilled(false);
        bInicio25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicio25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pListasInicioLayout = new javax.swing.GroupLayout(pListasInicio);
        pListasInicio.setLayout(pListasInicioLayout);
        pListasInicioLayout.setHorizontalGroup(
            pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListasInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasInicioLayout.createSequentialGroup()
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTituloInicio20, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTituloInicio21, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(bInicio21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lTituloInicio22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInicio22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasInicioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(lTituloInicio23, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addComponent(lTituloInicio24, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addComponent(lTituloInicio25, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pListasInicioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bInicio23, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bInicio24, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bInicio25, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pListasInicioLayout.setVerticalGroup(
            pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListasInicioLayout.createSequentialGroup()
                .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pListasInicioLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTituloInicio24)
                            .addComponent(lTituloInicio23)))
                    .addGroup(pListasInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTituloInicio25)
                            .addGroup(pListasInicioLayout.createSequentialGroup()
                                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bInicio18, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio19, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio20, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio23, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio24, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInicio25, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pListasInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lTituloInicio18)
                                        .addComponent(lTituloInicio19)
                                        .addComponent(lTituloInicio21)
                                        .addComponent(lTituloInicio20))
                                    .addComponent(lTituloInicio22))))))
                .addGap(25, 25, 25))
        );

        spListasInicio.setViewportView(pListasInicio);

        javax.swing.GroupLayout pInicioLayout = new javax.swing.GroupLayout(pInicio);
        pInicio.setLayout(pInicioLayout);
        pInicioLayout.setHorizontalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spGeneros, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addComponent(spListasInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(spAlbumPopular, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addComponent(pPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pInicioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spCancionTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );
        pInicioLayout.setVerticalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pPortada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281)
                .addComponent(spAlbumPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spListasInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pInicioLayout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(spCancionTendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(839, Short.MAX_VALUE)))
        );

        spInicio.setViewportView(pInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(spInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(spInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio1ActionPerformed
       mostrarCancionesListas(1);  
    }//GEN-LAST:event_bInicio1ActionPerformed

    private void bInicio25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio25ActionPerformed
        mostrarCancionesListas(8); 
    }//GEN-LAST:event_bInicio25ActionPerformed

    private void bInicio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio10ActionPerformed
       mostrarCancionesAlbum(1);  
    }//GEN-LAST:event_bInicio10ActionPerformed

    private void bInicio11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio11ActionPerformed
       mostrarCancionesAlbum(2); 
    }//GEN-LAST:event_bInicio11ActionPerformed

    private void bInicio12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio12ActionPerformed
        mostrarCancionesAlbum(3);  
    }//GEN-LAST:event_bInicio12ActionPerformed

    private void bInicio13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio13ActionPerformed
         mostrarCancionesAlbum(4);  
    }//GEN-LAST:event_bInicio13ActionPerformed

    private void bInicio14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio14ActionPerformed
        mostrarCancionesAlbum(5);  
    }//GEN-LAST:event_bInicio14ActionPerformed

    private void bInicio15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio15ActionPerformed
        mostrarCancionesAlbum(6); 
    }//GEN-LAST:event_bInicio15ActionPerformed

    private void bInicio16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio16ActionPerformed
        mostrarCancionesAlbum(7); 
    }//GEN-LAST:event_bInicio16ActionPerformed

    private void bInicio17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio17ActionPerformed
        mostrarCancionesAlbum(8);  
    }//GEN-LAST:event_bInicio17ActionPerformed

    private void bInicio18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio18ActionPerformed
        mostrarCancionesListas(1); 
    }//GEN-LAST:event_bInicio18ActionPerformed

    private void bInicio19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio19ActionPerformed
       mostrarCancionesListas(2); 
    }//GEN-LAST:event_bInicio19ActionPerformed

    private void bInicio20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio20ActionPerformed
        mostrarCancionesListas(3);
    }//GEN-LAST:event_bInicio20ActionPerformed

    private void bInicio21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio21ActionPerformed
        mostrarCancionesListas(4); 
    }//GEN-LAST:event_bInicio21ActionPerformed

    private void bInicio22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio22ActionPerformed
        mostrarCancionesListas(5); 
    }//GEN-LAST:event_bInicio22ActionPerformed

    private void bInicio23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio23ActionPerformed
        mostrarCancionesListas(6); 
    }//GEN-LAST:event_bInicio23ActionPerformed

    private void bInicio24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio24ActionPerformed
       mostrarCancionesListas(7); 
    }//GEN-LAST:event_bInicio24ActionPerformed

    private void bInicio26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio26ActionPerformed
        mostrarCancionesGeneros(1);
    }//GEN-LAST:event_bInicio26ActionPerformed

    private void bInicio27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio27ActionPerformed
        mostrarCancionesGeneros(2);
    }//GEN-LAST:event_bInicio27ActionPerformed

    private void bInicio28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio28ActionPerformed
         mostrarCancionesGeneros(3); 
    }//GEN-LAST:event_bInicio28ActionPerformed

    private void bInicio29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio29ActionPerformed
        mostrarCancionesGeneros(4);
    }//GEN-LAST:event_bInicio29ActionPerformed

    private void bInicio30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio30ActionPerformed
       mostrarCancionesGeneros(5); 
    }//GEN-LAST:event_bInicio30ActionPerformed

    private void bInicio31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio31ActionPerformed
        mostrarCancionesGeneros(6);
    }//GEN-LAST:event_bInicio31ActionPerformed

    private void bInicio32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio32ActionPerformed
        mostrarCancionesGeneros(7);
    }//GEN-LAST:event_bInicio32ActionPerformed

    private void bInicio33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio33ActionPerformed
        mostrarCancionesGeneros(8); 
    }//GEN-LAST:event_bInicio33ActionPerformed

    private void bInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio2ActionPerformed
        ventana.reproducirCancion("Macarena");
    }//GEN-LAST:event_bInicio2ActionPerformed

    private void bInicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio3ActionPerformed
        ventana.reproducirCancion("Viva La Vida");
    }//GEN-LAST:event_bInicio3ActionPerformed

    private void bInicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio4ActionPerformed
        ventana.reproducirCancion("Sweet Caroline");
    }//GEN-LAST:event_bInicio4ActionPerformed

    private void bInicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio5ActionPerformed
        ventana.reproducirCancion("Come and Get your Love");
    }//GEN-LAST:event_bInicio5ActionPerformed

    private void bInicio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio6ActionPerformed
        ventana.reproducirCancion("Someone Like You");
    }//GEN-LAST:event_bInicio6ActionPerformed

    private void bInicio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio7ActionPerformed
        ventana.reproducirCancion("Wake Me Up");
    }//GEN-LAST:event_bInicio7ActionPerformed

    private void bInicio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio8ActionPerformed
        ventana.reproducirCancion("We Will Rock You");
    }//GEN-LAST:event_bInicio8ActionPerformed

    private void bInicio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicio9ActionPerformed
        ventana.reproducirCancion("Gasolina");
    }//GEN-LAST:event_bInicio9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInicio1;
    private javax.swing.JButton bInicio10;
    private javax.swing.JButton bInicio11;
    private javax.swing.JButton bInicio12;
    private javax.swing.JButton bInicio13;
    private javax.swing.JButton bInicio14;
    private javax.swing.JButton bInicio15;
    private javax.swing.JButton bInicio16;
    private javax.swing.JButton bInicio17;
    private javax.swing.JButton bInicio18;
    private javax.swing.JButton bInicio19;
    private javax.swing.JButton bInicio2;
    private javax.swing.JButton bInicio20;
    private javax.swing.JButton bInicio21;
    private javax.swing.JButton bInicio22;
    private javax.swing.JButton bInicio23;
    private javax.swing.JButton bInicio24;
    private javax.swing.JButton bInicio25;
    private javax.swing.JButton bInicio26;
    private javax.swing.JButton bInicio27;
    private javax.swing.JButton bInicio28;
    private javax.swing.JButton bInicio29;
    private javax.swing.JButton bInicio3;
    private javax.swing.JButton bInicio30;
    private javax.swing.JButton bInicio31;
    private javax.swing.JButton bInicio32;
    private javax.swing.JButton bInicio33;
    private javax.swing.JButton bInicio4;
    private javax.swing.JButton bInicio5;
    private javax.swing.JButton bInicio6;
    private javax.swing.JButton bInicio7;
    private javax.swing.JButton bInicio8;
    private javax.swing.JButton bInicio9;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlbum1;
    private javax.swing.JLabel lNombreInicio10;
    private javax.swing.JLabel lNombreInicio11;
    private javax.swing.JLabel lNombreInicio12;
    private javax.swing.JLabel lNombreInicio13;
    private javax.swing.JLabel lNombreInicio14;
    private javax.swing.JLabel lNombreInicio15;
    private javax.swing.JLabel lNombreInicio16;
    private javax.swing.JLabel lNombreInicio17;
    private javax.swing.JLabel lNombreInicio2;
    private javax.swing.JLabel lNombreInicio3;
    private javax.swing.JLabel lNombreInicio4;
    private javax.swing.JLabel lNombreInicio5;
    private javax.swing.JLabel lNombreInicio6;
    private javax.swing.JLabel lNombreInicio7;
    private javax.swing.JLabel lNombreInicio8;
    private javax.swing.JLabel lNombreInicio9;
    private javax.swing.JLabel lTituloInicio10;
    private javax.swing.JLabel lTituloInicio11;
    private javax.swing.JLabel lTituloInicio12;
    private javax.swing.JLabel lTituloInicio13;
    private javax.swing.JLabel lTituloInicio14;
    private javax.swing.JLabel lTituloInicio15;
    private javax.swing.JLabel lTituloInicio16;
    private javax.swing.JLabel lTituloInicio17;
    private javax.swing.JLabel lTituloInicio18;
    private javax.swing.JLabel lTituloInicio19;
    private javax.swing.JLabel lTituloInicio2;
    private javax.swing.JLabel lTituloInicio20;
    private javax.swing.JLabel lTituloInicio21;
    private javax.swing.JLabel lTituloInicio22;
    private javax.swing.JLabel lTituloInicio23;
    private javax.swing.JLabel lTituloInicio24;
    private javax.swing.JLabel lTituloInicio25;
    private javax.swing.JLabel lTituloInicio26;
    private javax.swing.JLabel lTituloInicio27;
    private javax.swing.JLabel lTituloInicio28;
    private javax.swing.JLabel lTituloInicio29;
    private javax.swing.JLabel lTituloInicio3;
    private javax.swing.JLabel lTituloInicio30;
    private javax.swing.JLabel lTituloInicio31;
    private javax.swing.JLabel lTituloInicio32;
    private javax.swing.JLabel lTituloInicio33;
    private javax.swing.JLabel lTituloInicio4;
    private javax.swing.JLabel lTituloInicio5;
    private javax.swing.JLabel lTituloInicio6;
    private javax.swing.JLabel lTituloInicio7;
    private javax.swing.JLabel lTituloInicio8;
    private javax.swing.JLabel lTituloInicio9;
    private javax.swing.JPanel pAlbumPopular;
    private javax.swing.JPanel pCancionTendencias;
    private javax.swing.JPanel pGeneros;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pListasInicio;
    private javax.swing.JPanel pPortada;
    private javax.swing.JScrollPane spAlbumPopular;
    private javax.swing.JScrollPane spCancionTendencia;
    private javax.swing.JScrollPane spGeneros;
    private javax.swing.JScrollPane spInicio;
    private javax.swing.JScrollPane spListasInicio;
    private javax.swing.JTextArea taDescripcion;
    // End of variables declaration//GEN-END:variables
}
