/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import gestor.CargarImagenes;
import gestor.GestorConexion;
import java.util.List;
import javax.swing.JButton;
import vo.Cancion;

/**
 *
 * @author Elena
 */
public class PanelListas extends javax.swing.JPanel {
    private VentanaMusica ventana;
    /**
     * Creates new form PanelListas
     */
    public PanelListas(VentanaMusica ventana) {
        initComponents();
        this.ventana = ventana;
        GestorConexion gc = new GestorConexion();
        gc.conectarBBDD(null);
        
        CargarImagenes ci = new CargarImagenes(gc);
        
        javax.swing.SwingUtilities.invokeLater(() -> {

        ci.cargarListas(new JButton[]{
            bListas1, bListas2,bListas3, bListas4,
            bListas5, bListas6,bListas7, bListas8
        });

    });
        
        
    }
    //creo el metodo para mostrar las canciones en el el "PanelVacio"
    private void mostrarCancionesListas(int id_Lista) {
        // Obtener canciones usando ListasDaoImpl de la ventana principal
        List<Cancion> canciones = ventana.getCancionesPorLista(id_Lista);

        // Mostrar las canciones en PanelVacio
        ventana.mostrarCancionesEnVacio(canciones);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pListas = new javax.swing.JPanel();
        bListas1 = new javax.swing.JButton();
        bListas2 = new javax.swing.JButton();
        bListas3 = new javax.swing.JButton();
        bListas4 = new javax.swing.JButton();
        bListas5 = new javax.swing.JButton();
        bListas6 = new javax.swing.JButton();
        bListas7 = new javax.swing.JButton();
        bListas8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pListas.setBackground(new java.awt.Color(68, 68, 68));
        pListas.setEnabled(false);
        pListas.setPreferredSize(new java.awt.Dimension(294, 936));

        bListas1.setBorderPainted(false);
        bListas1.setContentAreaFilled(false);
        bListas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas1ActionPerformed(evt);
            }
        });

        bListas2.setBorderPainted(false);
        bListas2.setContentAreaFilled(false);
        bListas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas2ActionPerformed(evt);
            }
        });

        bListas3.setBorderPainted(false);
        bListas3.setContentAreaFilled(false);
        bListas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas3ActionPerformed(evt);
            }
        });

        bListas4.setBorderPainted(false);
        bListas4.setContentAreaFilled(false);
        bListas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas4ActionPerformed(evt);
            }
        });

        bListas5.setBorderPainted(false);
        bListas5.setContentAreaFilled(false);
        bListas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas5ActionPerformed(evt);
            }
        });

        bListas6.setBorderPainted(false);
        bListas6.setContentAreaFilled(false);
        bListas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas6ActionPerformed(evt);
            }
        });

        bListas7.setBorderPainted(false);
        bListas7.setContentAreaFilled(false);
        bListas7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas7ActionPerformed(evt);
            }
        });

        bListas8.setBorderPainted(false);
        bListas8.setContentAreaFilled(false);
        bListas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListas8ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Día Perfecto");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Te y galletas");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Multicolor Musical");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vida Organizada");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hits para sentirme adulta");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grammy en la Ducha");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Temazos para llorar");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Temas para Isabel II ");

        javax.swing.GroupLayout pListasLayout = new javax.swing.GroupLayout(pListas);
        pListas.setLayout(pListasLayout);
        pListasLayout.setHorizontalGroup(
            pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pListasLayout.createSequentialGroup()
                                .addComponent(bListas4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pListasLayout.createSequentialGroup()
                                .addComponent(bListas6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(pListasLayout.createSequentialGroup()
                                .addComponent(bListas7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pListasLayout.createSequentialGroup()
                                .addComponent(bListas8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pListasLayout.createSequentialGroup()
                                .addComponent(bListas5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pListasLayout.createSequentialGroup()
                                    .addComponent(bListas1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1))
                                .addGroup(pListasLayout.createSequentialGroup()
                                    .addComponent(bListas2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2))
                                .addGroup(pListasLayout.createSequentialGroup()
                                    .addComponent(bListas3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, Short.MAX_VALUE))))
        );
        pListasLayout.setVerticalGroup(
            pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListasLayout.createSequentialGroup()
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bListas1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)))
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bListas2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bListas3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListas4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListas5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListas6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListas7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pListasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(pListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListas8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pListasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(47, 47, 47)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pListas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bListas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas6ActionPerformed
        mostrarCancionesListas(6); 
    }//GEN-LAST:event_bListas6ActionPerformed

    private void bListas7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas7ActionPerformed
       mostrarCancionesListas(7); 
    }//GEN-LAST:event_bListas7ActionPerformed

    private void bListas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas8ActionPerformed
        mostrarCancionesListas(8); 
    }//GEN-LAST:event_bListas8ActionPerformed

    private void bListas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas1ActionPerformed
        mostrarCancionesListas(1);
    }//GEN-LAST:event_bListas1ActionPerformed

    private void bListas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas2ActionPerformed
        mostrarCancionesListas(2);
    }//GEN-LAST:event_bListas2ActionPerformed

    private void bListas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas3ActionPerformed
       mostrarCancionesListas(3);
    }//GEN-LAST:event_bListas3ActionPerformed

    private void bListas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas4ActionPerformed
        mostrarCancionesListas(4); 
    }//GEN-LAST:event_bListas4ActionPerformed

    private void bListas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListas5ActionPerformed
       mostrarCancionesListas(5);
    }//GEN-LAST:event_bListas5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bListas1;
    private javax.swing.JButton bListas2;
    private javax.swing.JButton bListas3;
    private javax.swing.JButton bListas4;
    private javax.swing.JButton bListas5;
    private javax.swing.JButton bListas6;
    private javax.swing.JButton bListas7;
    private javax.swing.JButton bListas8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pListas;
    // End of variables declaration//GEN-END:variables
}
