/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventana;

import gestor.CargarImagenes;
import gestor.GestorConexion;
import java.util.List;
import javax.swing.JButton;
import vo.Cancion;

/**
 *
 * @author Elena
 */
public class PanelArtistas extends javax.swing.JPanel {
     private VentanaMusica ventana;
    /**
     * Creates new form PanelArtistas
     */
     private int id_artista = -1;
    public PanelArtistas(VentanaMusica ventana) {
        initComponents();
         this.ventana = ventana;
        GestorConexion gc = new GestorConexion();
        gc.conectarBBDD(null);

        CargarImagenes ci = new CargarImagenes(gc);

        JButton[] botones = {
            bArtistas1, bArtistas2, bArtistas3, bArtistas4,
            bArtistas5, bArtistas6, bArtistas7, bArtistas8
        };

        int[] ids = {1, 4, 5, 13, 16, 20, 23, 30};

        for (int i = 0; i < botones.length; i++) {
            ci.cargarArtistas(new JButton[]{botones[i]}, ids[i]);
        }

        
    }

    //creo el metodo para mostrar las canciones en el el "PanelVacio"
    private void mostrarCancionesArtistas(int id_Artista) {
        // Obtener canciones usando ArtistasDaoImpl de la ventana principal
        List<Cancion> canciones = ventana. getCancionesPorArtista(id_Artista);

        // Mostrar las canciones en PanelVacio
        ventana.mostrarCancionesEnVacio(canciones);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pArtistas = new javax.swing.JPanel();
        bArtistas1 = new javax.swing.JButton();
        bArtistas2 = new javax.swing.JButton();
        bArtistas3 = new javax.swing.JButton();
        bArtistas4 = new javax.swing.JButton();
        bArtistas5 = new javax.swing.JButton();
        bArtistas6 = new javax.swing.JButton();
        bArtistas7 = new javax.swing.JButton();
        bArtistas8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pArtistas.setBackground(new java.awt.Color(68, 68, 68));
        pArtistas.setEnabled(false);
        pArtistas.setPreferredSize(new java.awt.Dimension(294, 936));

        bArtistas1.setBorderPainted(false);
        bArtistas1.setContentAreaFilled(false);
        bArtistas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas1ActionPerformed(evt);
            }
        });

        bArtistas2.setBorderPainted(false);
        bArtistas2.setContentAreaFilled(false);
        bArtistas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas2ActionPerformed(evt);
            }
        });

        bArtistas3.setBorderPainted(false);
        bArtistas3.setContentAreaFilled(false);
        bArtistas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas3ActionPerformed(evt);
            }
        });

        bArtistas4.setBorderPainted(false);
        bArtistas4.setContentAreaFilled(false);
        bArtistas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas4ActionPerformed(evt);
            }
        });

        bArtistas5.setBorderPainted(false);
        bArtistas5.setContentAreaFilled(false);
        bArtistas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas5ActionPerformed(evt);
            }
        });

        bArtistas6.setBorderPainted(false);
        bArtistas6.setContentAreaFilled(false);
        bArtistas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas6ActionPerformed(evt);
            }
        });

        bArtistas7.setBorderPainted(false);
        bArtistas7.setContentAreaFilled(false);
        bArtistas7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas7ActionPerformed(evt);
            }
        });

        bArtistas8.setBorderPainted(false);
        bArtistas8.setContentAreaFilled(false);
        bArtistas8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArtistas8ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Taylor Swift");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bad Bunny");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amaia");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adele");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avicii");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("The Weeknd");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Queen");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lana Del Rey");

        javax.swing.GroupLayout pArtistasLayout = new javax.swing.GroupLayout(pArtistas);
        pArtistas.setLayout(pArtistasLayout);
        pArtistasLayout.setHorizontalGroup(
            pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(65, 112, Short.MAX_VALUE))
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addComponent(bArtistas7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(pArtistasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bArtistas8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 106, Short.MAX_VALUE))))
        );
        pArtistasLayout.setVerticalGroup(
            pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pArtistasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bArtistas7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pArtistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistasLayout.createSequentialGroup()
                        .addComponent(bArtistas8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(47, 47, 47))))
        );

        jScrollPane1.setViewportView(pArtistas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bArtistas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas6ActionPerformed
       id_artista = 20;
       mostrarCancionesArtistas(20);
    }//GEN-LAST:event_bArtistas6ActionPerformed

    private void bArtistas7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas7ActionPerformed
        id_artista = 23;
        mostrarCancionesArtistas(23); 
    }//GEN-LAST:event_bArtistas7ActionPerformed

    private void bArtistas8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas8ActionPerformed
        id_artista = 30;
        mostrarCancionesArtistas(30); 
    }//GEN-LAST:event_bArtistas8ActionPerformed

    private void bArtistas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas1ActionPerformed
        id_artista = 1;
        mostrarCancionesArtistas(1);
    }//GEN-LAST:event_bArtistas1ActionPerformed

    private void bArtistas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas2ActionPerformed
        id_artista = 4;
        mostrarCancionesArtistas(4);
    }//GEN-LAST:event_bArtistas2ActionPerformed

    private void bArtistas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas3ActionPerformed
        id_artista = 5;
        mostrarCancionesArtistas(5); 
    }//GEN-LAST:event_bArtistas3ActionPerformed

    private void bArtistas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas4ActionPerformed
        id_artista = 13;
        mostrarCancionesArtistas(13); 
    }//GEN-LAST:event_bArtistas4ActionPerformed

    private void bArtistas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArtistas5ActionPerformed
        id_artista = 16;
        mostrarCancionesArtistas(16);
    }//GEN-LAST:event_bArtistas5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArtistas1;
    private javax.swing.JButton bArtistas2;
    private javax.swing.JButton bArtistas3;
    private javax.swing.JButton bArtistas4;
    private javax.swing.JButton bArtistas5;
    private javax.swing.JButton bArtistas6;
    private javax.swing.JButton bArtistas7;
    private javax.swing.JButton bArtistas8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pArtistas;
    // End of variables declaration//GEN-END:variables
}
